from typing import Protocol

class RuminationStrategy(Protocol):

    def calculer_lait(self, vache:"vache", panse_avant) -> float : ...
    def stocker_lait(self, vache:"vache", lait) -> None : ...
    def post_rumination(self, vache:"vache", panse_avant, lait) -> None : ...
